import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';

export const THEME = {
  light: {
    background: '#ffffff',
    foreground: '#0f1419',
    card: '#f7f8f8',
    cardForeground: '#0f1419',
    popover: '#ffffff',
    popoverForeground: '#0f1419',
    primary: '#1e9df1',
    primaryForeground: '#ffffff',
    secondary: '#0f1419',
    secondaryForeground: '#ffffff',
    muted: '#e5e5e6',
    mutedForeground: '#0f1419',
    accent: '#e3ecf6',
    accentForeground: '#1e9df1',
    destructive: '#f4212e',
    border: '#e1eaef',
    input: '#f7f9fa',
    ring: '#1da1f2',
    radius: '0.625rem',
    chart1: '#1e9df1',
    chart2: '#00b87a',
    chart3: '#f7b928',
    chart4: '#17bf63',
    chart5: '#e0245e',
  },
  dark: {
    background: '#000000',
    foreground: '#e7e9ea',
    card: '#17181c',
    cardForeground: '#d9d9d9',
    popover: '#000000',
    popoverForeground: '#e7e9ea',
    primary: '#1c9cf0',
    primaryForeground: '#ffffff',
    secondary: '#f0f3f4',
    secondaryForeground: '#0f1419',
    muted: '#181818',
    mutedForeground: '#72767a',
    accent: '#061622',
    accentForeground: '#1c9cf0',
    destructive: '#f4212e',
    border: '#242628',
    input: '#22303c',
    ring: '#1da1f2',
    radius: '0.625rem',
    chart1: '#1e9df1',
    chart2: '#00b87a',
    chart3: '#f7b928',
    chart4: '#17bf63',
    chart5: '#e0245e',
  },
};

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};